# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_profile_image'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ManyToManyField(default='-99', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default='-99', on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.IntegerField(choices=[(0, 'location'), (1, 'tag')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sns_type',
            field=models.IntegerField(choices=[(0, 'facebook'), (1, 'kakaotalk')], default=0),
        ),
    ]
