# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160416_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='store',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='filter',
            field=models.ManyToManyField(to='posts.Filter'),
        ),
    ]
