# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160502_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default='none', max_length=1000, verbose_name='location'),
        ),
    ]
