# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160502_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='meta_data',
            field=models.CharField(default='none', max_length=1000, verbose_name='meta_data'),
        ),
    ]
