# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160417_1659'),
        ('posts', '0007_photo_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use', models.IntegerField(choices=[(0, 'not'), (1, 'use')], default=0)),
                ('value', models.CharField(default='value_none', max_length=1000, verbose_name='special_key')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Store')),
                ('user', models.ForeignKey(default='-99', on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
