# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key',
            new_name='secretStoreKey',
        ),
    ]
