# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160509_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretstorekey',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Photo'),
        ),
    ]
