# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_secretstorekey_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretstorekey',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='secret_key',
            field=models.ForeignKey(default=-99, on_delete=django.db.models.deletion.CASCADE, to='posts.SecretStoreKey'),
        ),
    ]
