# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_photo_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='secret_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.SecretStoreKey'),
        ),
    ]
