# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20160511_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='secret_key',
        ),
    ]
