# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20160511_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='contents',
            field=models.TextField(default='none', verbose_name='contents'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='none', max_length=1000, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='secret_key',
            field=models.ForeignKey(default=-99, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.SecretStoreKey'),
        ),
    ]
