# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20160517_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to=posts.models.filepath_img_profile, verbose_name='\ud504\ub85c\ud544 \uc774\ubbf8\uc9c0'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='secret_key',
            field=models.ForeignKey(default=-99, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.SecretStoreKey'),
        ),
    ]
