# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20160518_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img_profile',
        ),
        migrations.AddField(
            model_name='secretstorekey',
            name='domination',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='secret_key',
            field=models.ForeignKey(default=-99, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.SecretStoreKey'),
        ),
    ]
