# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
