# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='deviceID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='nickname'),
        ),
    ]
