# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160416_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='/url'),
        ),
    ]
